server:
  port: 9091
spring:
  application:
    name: vxpt-user
  datasource:
    url: jdbc:postgresql://postgresql:8432/postgres
    username: vxpt
    password: vxpt1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://tencent:9090/eureka
  instance:
    prefer-ip-address: true # 服务实例显示ip而不是显示主机名
    # 实例名称
    instance-id: ${spring.application.name}:${server.port}
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 5
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 10

token:
  aes:
    key: 123456789
  expireSecond: 86400   # 24小时，单位秒