server:
  port: 9091
spring:
  application:
    name: vxpt-user
  datasource:
    url: jdbc:postgresql://postgresql:8432/postgres
    username: vxpt
    password: vxpt1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://tencent:9090/eureka
  instance:
    prefer-ip-address: true # 服务实例显示ip而不是显示主机名
    # 实例名称
    instance-id: ${spring.application.name}:${server.port}

token:
  aes:
    key: 123456789
  expireSecond: 86400   # 24小时，单位秒