server:
  port: 9092

 # 注册到Eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
  instance:
    hostname: vxpt-gateway
    prefer-ip-address: false  #是否使用ip注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #ip:port

spring:
  application:
    name: vxpt-gateway
  cloud:
    gateway:
      routes:
        - id: vxpt-user
          uri: lb://vxpt-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1


