# Tomcat
server:
  port: 8899

#spring
spring:
  profiles:
    active: dev
  datasource:
    #引用项目中的数据库文件
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:sqlite/bbs.db
    username:
    password:

